import logging, time, os, asyncio, pickle, random
from dotenv import load_dotenv
from telegram import Update
from telegram.ext import ApplicationBuilder, ContextTypes, CommandHandler
from google import genai
from google.genai import types
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload
from google.auth.transport.requests import Request

# Load Env
load_dotenv()
TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
TOKEN_FILE = 'token.json'

# Konfigurasi Judul
ONE_WORD_LIST = ["Sad", "Lonely", "Broken", "Lost", "Pain", "Alone", "Tears", "Help", "Miss", "Gone", "Hurt", "Why", "Cold", "Poor", "Wait"]
EMOTE_LIST = ["😿", "😭", "💔", "🥀", "🌧️", "🥺"]
FULL_HASHTAGS = "#aiandcats #aicats #kitten #catlovers #catshorts"

logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s', level=logging.INFO)
client = genai.Client(api_key=GOOGLE_API_KEY)

def get_authenticated_service():
    creds = None
    if os.path.exists(TOKEN_FILE):
        with open(TOKEN_FILE, 'rb') as token: creds = pickle.load(token)
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
            with open(TOKEN_FILE, 'wb') as token: pickle.dump(creds, token)
        else: raise Exception("Token rusak/expired.")
    return build('youtube', 'v3', credentials=creds)

def upload_video(path, title, desc, tags):
    youtube = get_authenticated_service()
    body = {
        'snippet': {'title': title, 'description': desc, 'tags': tags, 'categoryId': '22'},
        'status': {'privacyStatus': 'public', 'selfDeclaredMadeForKids': False}
    }
    media = MediaFileUpload(path, chunksize=-1, resumable=True)
    req = youtube.videos().insert(part=','.join(body.keys()), body=body, media_body=media)
    resp = None
    while resp is None: status, resp = req.next_chunk()
    return resp['id']

async def shorts_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    prompt = ' '.join(context.args)
    if not prompt: return await update.message.reply_text("❌ Mana promptnya? Contoh: /shorts Sad cat in rain")
    
    final_title = f"{random.choice(ONE_WORD_LIST)} {random.choice(EMOTE_LIST)} {FULL_HASHTAGS}"
    msg = await update.message.reply_text(f"🎬 **Proses...**\n🏷 Judul: `{final_title}`")
    
    try:
        loop = asyncio.get_running_loop()
        def run_veo():
            return client.models.generate_videos(model='veo-3.1-generate-preview', prompt=prompt, config=types.GenerateVideosConfig(aspect_ratio="9:16", resolution="1080p"))
        
        op = await loop.run_in_executor(None, run_veo)
        while not op.done: await asyncio.sleep(5)
        
        if not op.result or not op.result.generated_videos: return await msg.edit_text("❌ Gagal generate video.")
        
        filename = f"veo_{int(time.time())}.mp4"
        op.result.generated_videos[0].video.save(filename)
        await msg.edit_text("✅ Uploading ke YouTube...")
        
        desc = f"{final_title}\n\nPrompt: {prompt}\nGenerated by AI Veo."
        tags = ["Shorts", "Cat", "Sad", "AI"]
        
        def run_upload(): return upload_video(filename, final_title, desc, tags)
        
        vid_id = await loop.run_in_executor(None, run_upload)
        await msg.edit_text(f"🚀 **Sukses!**\n🔗 https://youtube.com/shorts/{vid_id}")
        if os.path.exists(filename): os.remove(filename)
            
    except Exception as e: await msg.edit_text(f"❌ Error: {str(e)}")

if __name__ == '__main__':
    if not TELEGRAM_TOKEN: exit()
    app = ApplicationBuilder().token(TELEGRAM_TOKEN).build()
    app.add_handler(CommandHandler("shorts", shorts_handler))
    print("🤖 Bot Active")
    app.run_polling()
